# エラー(例外)の読み方

{{ TOC }}

## 概要

プログラムに誤りがあると、そこでエラーが発生して停止することがあります。
たとえばif文のコロン(:)を忘れたり、インデントの深さを間違うといった文法レベルの問題から、
0を持つ変数で割り算してしまうといった間違いです。

間違いを直して正しいプログラムを作るには、
停止時のエラー内容である「スタックトレース」を呼んで問題箇所を把握し修正する必要があります。

また、プログラムの文法や使い方自体は正しいものの、
自分が意図した通りにプログラムが動いていない場合もあります。
そのような場合はプログラムの動きを追って問題箇所を探すことが必要になります。

## プログラムの間違い

数行、数十行のプログラムならともかく、ある程度の大きさのプログラムを書くと必ず間違いがあります。
間違いにもいろいろあり、Pythonが「*エラー*」として実行を停止してしまうものから、
Pythonのプログラムとしては間違っていないためエラーにはならいものの、プログラマの意図通りに動いていないものなどがあります。

本ページではそれらの間違いをどのように正すかについて扱います。

なお、「発生することが期待されるエラー」というものがプログラミングにはあります。
たとえば外部サーバーから情報を取ってくるプログラムで、その相手のサーバーがダウンしている場合のエラーなどです。
そういったトラブルは例外処理と呼ばれる手法で対応しますが、それは例外処理のページにて解説します。

## エラー

プログラムに文法的な間違いがあった場合に、
Pythonは「どこが、どういう理由で間違っている」ということを、エラーとして出力します。

エラーは大まかに2つあり、「*文法エラー*」と「*実行時エラー*」と呼ばれるものです。

文法エラーはモジュールを読み込んだ段階でPythonが上から下までそれをチェックして、
そこに誤りがあれば発生します。
ここに間違いがあれば、プログラムは実行すらされません。

文法チェックに問題がなかったプログラムであっても、その実行時にエラーが発生することがあります。
実行時エラーと呼ばれるもので、例えば宣言されていない変数を参照しようとしたり、
0で割り算をした場合に発生します。

### 文法エラー

例えば以下のようなプログラムがあるとしましょう。
プログラムは「sample.py」というプログラムファイルに書かれています。

#### プログラム: 2行目に間違いがある

```python
print(1)
if True
  print(2)
print(3)
```

このプログラムは2行目のif文に間違いがあります。
正しくは「if True:」となるべきところを、「:」を忘れています。
これはPythonの文法として誤りがあります。

このプログラムを実行すると、以下のようなエラー出力が得られます。

#### コンソール: 実行するとエラーが発生

```text
$ python3 sample.py
  File "sample.py", line 2
    if True
          ^
SyntaxError: invalid syntax
```

エラーの出力を上から順に確認すると、以下のことがわかります。

* sample.pyというファイルの2行目
* 「if True」の後ろ側に問題がある
* 「SyntaxError: invalid syntax」というエラーが発生

どこでどう間違えているか出力しているため、修正箇所はひと目でわかります。

エラー出力以外に着目してほしいのは「print(1)」が実行されていないことです。
エラー箇所は2行目にあるものの、1行目に間違いはありません。
上から順に実行されるのであれば、1行目は実行されて、実行結果に「1」と表示されそうな気がします。

これには理由があり、Pythonは「文法チェックを実行前に行う」という動きをしているためです。
実際に実行されるのは文法チェックをパスした後なので、文法に誤りがあると実行する段階まで進めません。

### 実行時エラー

文法チェックにパスをしたら、Pythonのプログラムが実行されます。

実行される段階で発生したエラーは「実行時エラー」と呼ばれており、
そのプログラムファイルのなかのその行が実行されたタイミングでエラーが発生します。

たとえば、以下の文法的には間違いがないプログラムがあるとします。

```python
print(1)
if True:
  a = 5 / 0
  print(2)
print(3)
```

このプログラムは文法的にはあっていますが、
3行目の「a = 5 / 0」が「0による割り算」なので間違っています。

これを実行すると、以下のようなエラーが発生します。

```text
$ python3 sample.py
1
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    a = 5 / 0
ZeroDivisionError: division by zero
```

エラーの内容を読むと以下のことが分かります。

* sample.pyというファイルの3行目
* 「a = 5 / 0」に問題がある
* 「ZeroDivisionError: division by zero」というエラーが発生

「Division」は割り算という意味なので、0による割り算エラーが発生しているということです。

先ほどの文法エラーと頃なるのは出力の1行目に「1」という出力があることです。
これはプログラムの1行目にある「print(1)」が実行されているためです。

実行時エラーはその行が実行されて始めてエラーとなるため、
その行にいたるまでの他の行は実行されています。
ただ、エラーが発生した以降の処理は出力に「print(2)」に相当する「2」がないことからも、
実行されていないことが分かります。

### 検知されないエラー

実行時エラーは実行されることで始めてエラーであると分かります。
逆にいえば「エラーがあっても、それが実行されないとエラーにならない」ということです。

たとえば先ほどのプログラムを少し書き換えて、以下のようなコードとします。

```python
print(1)
if False:
  a = 5 / 0
  print(2)
print(3)
```

if文の条件式がFalseとなっているため、そのコードブロックは実行されません。
ただ、そのコードブロック中の処理にはエラーとなる「a = 5 / 0」があります。

このプログラムを実行すると、以下のような出力となりエラーは発生しません。

```text
$ python3 sample3.py
1
3
```

実行時エラーは実行時にはじめて発生します。
条件分岐の関係で「実行したり実行されなかったりする行」の問題は検知しづらい場合があります。

実行時にエラーとなることを防ぐためには、きちんとした「*テスト*」が必要です。
ただ、初心者は他に優先して学ぶべきことが多いので、
ある程度のレベルに達するまで気を配る必要はないかもしれません。


## 代表的なエラー

### 宣言されていない変数や関数の利用

### リストの範囲外のアクセス

### 0による割り算

### 外部環境に依存するエラー
