<!DOCTYPE html>
<html lang="ja-JP">
 <head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta content="Sample Description" name="description"/>
  <meta content="Yuichi Ito" name="author"/>
  <link href="./asset/favicon.ico" rel="icon"/>
  <title>
   Python入門
  </title>
  <!-- Bootstrap -->
  <link href="./assets/css/bootstrap.css" rel="stylesheet"/>
  <link href="./assets/css/bootstrap-theme.css" rel="stylesheet"/>
  <link href="./assets/css/bootstrap_u1.css" rel="stylesheet"/>
  <!-- Font -->
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet">
   <!-- Code Highlight -->
   <link href="./assets/css/codehilite_colorful.css" rel="stylesheet"/>
   <!-- Custom -->
   <link href="./assets/css/font-awesome.min.css" rel="stylesheet"/>
   <link href="./assets/icomoon/style.css" rel="stylesheet"/>
   <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
   <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </link>
 </head>
 <body>
  <div class="backgroundLayer">
   <!-- Fixed navbar -->
   <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
     <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
       <span class="sr-only">
        Toggle navigation
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
      </button>
      <a class="navbar-brand " href="#">
       Python
      </a>
     </div>
     <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
       <li class="">
        <a href="">
         Navi
        </a>
       </li>
       <li class="">
        <a href="">
         QA
        </a>
       </li>
       <li class="">
        <a href="">
         Books
        </a>
       </li>
      </ul>
     </div>
    </div>
   </nav>
   <div class="container">
    <div class="u1-header">
     <a href="./" style=" text-decoration: none;">
      <div class="u1-title">
       Python Boot Camp
      </div>
      <p class="lead u1-description">
       プログラミング言語Python訓練プログラム
      </p>
     </a>
    </div>
    <div class="row">
     <div class="col-sm-8 u1-main">
      <!-- GENERATED HTML START -->
      <!-- GENERATED HTML START -->
      <h2 id="header-1">
       例外処理の基礎
      </h2>
      <div class="no_bullets" id="toc_container">
       <p class="toc_title">
        本記事の内容
       </p>
       <ul class="toc_list">
        <li>
         <a href="#header-1">
          例外処理の基礎
         </a>
         <ul>
          <li>
           <a href="#header-2">
            概要
           </a>
          </li>
          <li>
           <a href="#header-3">
            例外処理とはなにか
           </a>
          </li>
          <li>
           <a href="#header-4">
            例外処理のやりかた
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
      <h3 id="header-2">
       概要
      </h3>
      <p>
       あとで書く
      </p>
      <h3 id="header-3">
       例外処理とはなにか
      </h3>
      <p>
       例外処理は名前を聞いてわかるように「例外(エラー)」に対する処理です。
この例外は簡単に言ってしまえば、「期待されない動き」のことで、たとえば0での除算などがあげられます。
算数や数学で学んだことがあるかもしれませんが、「0で何かを割る」というのは数学ではやってはいけないルールです。
そのため、Pythonでもこの処理を実行しようとするとエラーになります。
      </p>
      <p>
       試しにターミナルで実行してみると以下のようなエラー表示が確認できます。
      </p>
      <div class="codehilite">
       <pre><span></span>&gt;&gt;&gt; 5 / 0
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
ZeroDivisionError: division by zero
</pre>
      </div>
      <p>
       出力されたエラーメッセージを読んでもらうとわかるように、
0によるdivision(割り算)によりZeroDivisionErrorが発生していることがわかります。
このエラーが発生すると処理が中断されてしまいます。
      </p>
      <p>
       以下のようなバグを含むコードを用意します。0除算のバグの前後に Print 文があるため、
どこでエラーが発生するか確認できます。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">def</span> <span class="nf">test</span><span class="p">():</span>
  <span class="k">print</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
  <span class="mi">5</span> <span class="o">/</span> <span class="mi">0</span>
  <span class="k">print</span><span class="p">(</span><span class="mi">2</span><span class="p">)</span>

<span class="n">test</span><span class="p">()</span>
<span class="k">print</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
</pre>
      </div>
      <p>
       上記のプログラムを実行してみます。
      </p>
      <div class="codehilite">
       <pre><span></span>1
Traceback (most recent call last):
  File "test.py", line 6, in &lt;module&gt;
    test()
  File "test.py", line 3, in test
    5 / 0
ZeroDivisionError: division by zero
</pre>
      </div>
      <p>
       出力されるのは1だけであり、2は出力されていません。
2が出力される前に「5を0で割る」という処理があり、
そこでエラーが発生してprint(2)を実行する前に処理を打ち切ってしまっているためです。
この「数字を0で割る」という処理はそもそもプログラムとして実装されるべきではありません。
上記のような直接的なバグコードを書くことはもちろん、
たとえばどのような数字が入っているかわからない変数aを変数bで割る場合は、
割る前にbの値が0でないかをチェックし、0の場合は割らないようにするなどの対処が必要です。
例えば以下のようなコードとなります。
      </p>
      <p>
       list_ = [4,2,8,0,9,1,5]
for i in list_:
  if i == 0:
    print('SKIP')
  else:
    print(5 / i)
      </p>
      <h1>
       1.25
      </h1>
      <h1>
       2.5
      </h1>
      <h1>
       0.625
      </h1>
      <h1>
       skip
      </h1>
      <h1>
       0.5555555555555556
      </h1>
      <h1>
       5.0
      </h1>
      <h1>
       1.0
      </h1>
      <p>
       0除算のようなエラーは必ず発生しないように注意を払う必要があります。
ただ、注意深くコードを書くことによりすべてのエラーが避けられるかというと、そうではありません。
たとえば「サーバからデータを取ってくる」というネットワークを使ったプログラムを作成する場合、
「サーバに接続できるか」は自分が注意深くコードを書くかどうかというよりも、
実行するマシンがネットワークにそもそも繋がっているか、つながっていてもサーバへのリーチャビリティはあるか、
といったことなどに依存します。
このような処理をする場合はその例外を正しく取り扱うために例外処理が必要です。
      </p>
      <h3 id="header-4">
       例外処理のやりかた
      </h3>
      <p>
       例外に対する例外処理が必要なことはわかっていただけたと思います。
ここではその例外処理をどのようにして実装するかという「概念」を学びたいと思います。
      </p>
      <p>
       まず、例外処理はPython以前からある思想です。
例外は言語に関係なく発生するので当然です。
ただ、その例外処理の実装スタイルには大まかに分けて2つあります。
ひとつめはC言語などで使われる「返り値チェック」を使うものです。
そして2つめはJavaなどで使われる「try/catch」を使うものです。
PythonはJavaと同じく後者を使うのですが、前者も知っておく必要があるので先に説明します。
      </p>
      <p>
       C言語のような「返り値チェック」の例外処理ですが、歴史的にはこちらのほうが古いです。
その方式を簡単に言ってしまうと「ある関数を呼び出した時の返り値」が例外の値でないかをチェックするというものです。
      </p>
      <p>
       以下の図を見てください。
      </p>
      <p class="blog-img">
       <img alt="image" class="img-responsive" src="./1090_image/01.jpg"/>
      </p>
      <p>
       ここでは関数Aがあり、それは「ある処理に失敗したら、返り値として-1を返す」という動きをすると決められています。
自分でこの返り値のルールを作ることもあるでしょうし、
すでに存在している関数のドキュメントにそう書かれていることもあります。
このような関数を使う場合、その返り値を受取、それがエラーの結果出ないことを確認する必要があります。
Python にもこのタイプの関数(メソッド)があり、例えば以下の文字列の find メソッドがあげられます。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="n">index</span> <span class="o">=</span> <span class="s1">'12345'</span><span class="o">.</span><span class="n">find</span><span class="p">(</span><span class="s1">'34'</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="n">index</span><span class="p">)</span>
<span class="c1"># 2</span>

<span class="n">index</span> <span class="o">=</span> <span class="s1">'12345'</span><span class="o">.</span><span class="n">find</span><span class="p">(</span><span class="s1">'hello'</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="n">index</span><span class="p">)</span>
<span class="c1"># -1</span>
</pre>
      </div>
      <p>
       このメソッドはある文字列がその文字列オブジェクトのどこにあるかを返します。
ひとつめのサンプルは含まれているため位置を返し、ふたつめのサンプルは含まれていないため、「-1」を返しています。
例えばこの返り値の特性を使って「ある文字列が別の文字列に含まれるか」を確認する関数を作ることができます。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">def</span> <span class="nf">contains</span><span class="p">(</span><span class="n">text1</span><span class="p">,</span> <span class="n">text2</span><span class="p">):</span>
  <span class="n">index</span> <span class="o">=</span> <span class="n">text1</span><span class="o">.</span><span class="n">find</span><span class="p">(</span><span class="n">text2</span><span class="p">)</span>
  <span class="k">if</span><span class="p">(</span><span class="n">index</span> <span class="o">==</span> <span class="o">-</span><span class="mi">1</span><span class="p">):</span>
    <span class="k">return</span> <span class="bp">False</span>
  <span class="k">else</span><span class="p">:</span>
    <span class="k">return</span> <span class="bp">True</span>    

<span class="k">print</span><span class="p">(</span><span class="n">contains</span><span class="p">(</span><span class="s1">'12345'</span><span class="p">,</span> <span class="s1">'34'</span><span class="p">))</span>
<span class="c1"># True</span>

<span class="k">print</span><span class="p">(</span><span class="n">contains</span><span class="p">(</span><span class="s1">'12345'</span><span class="p">,</span> <span class="s1">'hello'</span><span class="p">))</span>
<span class="c1"># False</span>
</pre>
      </div>
      <p>
       上記コードの関数はかなり冗長ですが、返り値が -1 であれば「含まれないためFalse」、
そうでなければ「含まれるためTrue」としています。
      </p>
      <p>
       上記のプログラムであれば単に含まれるか含まれないかの判定ですが、
もし仮に「文字列が含まれていなければ処理を中断しなければならない」とした場合、
仮に返り値が-1であれば処理に失敗しているので、処理の中断なり別の回避策なりが必要です。
      </p>
      <p>
       この関数の返り値のチェック以外にも、関数の引数に「ポインタと呼ばれている参照」を渡し、
そこに関数内で特定の値をセットするという方法もあります。
関数を呼び出した側でそのポインタの値をチェックすれば、引数と同じく成功したか失敗したかがわかります。
このような形でポインタを使うところはC言語特有なので、
比較的新しい高級言語しか使わない人には慣れない使い方かと思いますが、
基本的には関数の返り値のチェックと大差はありません。
これらがC言語などの手続き型言語で使われる代表的な例外処理方式です。
      </p>
      <h4>
       Try/Exception(Catch)方式
      </h4>
      <p>
       次にJavaで使われるtry/catchによる例外処理です。
プログラミング言語の文法としてtry/catch方式の例外処理がサポートされている場合に利用可能で、
Pythonもこれをサポートしています。
C 言語はサポートしていません。
Python にて自分でコードを書く場合はC方式の例外処理を実装することも可能ですが、
ほかの人のコードを利用する場合はその例外処理をtry/catchで対処する必要があり、
なおかつCのスタイルで例外処理を使うとコードも煩雑になるので、
特に理由がないかぎりはtry/catchに沿った例外処理を使ったほうがよいと思います。
      </p>
      <p>
       とりあえず Java の Try/Catchをどのように使うか見てみましょう。以下の図を見てください。
      </p>
      <p class="blog-img">
       <img alt="image" class="img-responsive" src="./1090_image/02.jpg"/>
      </p>
      <p>
       try/catch方式は簡単です。例外が発生する可能性があり、
その対処が必要な箇所をtryスコープ(Javaだと中括弧{}のブロック)で囲みます。
このスコープ内でエラーが発生すると、その後ろにあるcatchスコープまでジャンプします。
エラーが発生したあとのtryスコープ内のコードは実行されないので注意してください。
上記図で言うと、処理2の前にエラーが発生すると、処理2は実行されません。
      </p>
      <p>
       また、tryスコープの中でエラーが発生しなかった場合はcatchのスコープ内の処理は実行されません。
tryの中でエラーが起きようと起きまいと、try/catchの後にあるコードは実行されます。
もしエラーが発生した場合に処理を打ち切りたいのであれば、catchの中でプログラムを終了させるなり、
returnで関数を抜けてしまうなりする必要があります。
      </p>
      <p>
       try/catchについては実際にPythonで使い方を学ぶと理解できると思いますので、
詳しい話をするのはここでは控えて、使いながら学んでいきたいと思います。
      </p>
      <h4>
       Pythonのtry/catch
      </h4>
      <p>
       Pythonのtry/catchは簡単です。まず一番シンプルな使い方は以下のようなものになります。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">print</span><span class="p">(</span><span class="s1">'1: outside of try/catch'</span><span class="p">)</span>

<span class="k">try</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'2: inside of try scope'</span><span class="p">)</span>
  <span class="mi">5</span> <span class="o">/</span> <span class="mi">0</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'3: inside of try scope'</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'4: inside of except(catch) scope'</span><span class="p">)</span>

<span class="k">print</span><span class="p">(</span><span class="s1">'5: outside of try/catch'</span><span class="p">)</span>
</pre>
      </div>
      <p>
       try/catchのcatchはPythonではexceptになっていますが、それ以外は先程説明したものとまったく同じです。
tryの中でエラーが発生すれば、それ以後のtry内の処理を打ち切ってexceptにジャンプします。
      </p>
      <p>
       見てもらうと分かるように今回はわざとtry ブロックの中で「5/0」でエラーを発生させています。
これを実行すると以下のようになります。
      </p>
      <div class="codehilite">
       <pre><span></span># python3 test.py
1: outside of try/catch
2: inside of try scope
4: inside of except(catch) scope
5: outside of try/catch
</pre>
      </div>
      <p>
       上記出力を見てわかるように、5/0のエラー発生後のコードであるprint('3: inside of try scope') は実行されずに、
exceptにジャンプしてその中の処理を実施しています。
試しにこの5 / 0をコメントアウトして実行してみます。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">print</span><span class="p">(</span><span class="s1">'1: outside of try/catch'</span><span class="p">)</span>

<span class="k">try</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'2: inside of try scope'</span><span class="p">)</span>
  <span class="c1"># 5 / 0</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'3: inside of try scope'</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="s1">'4: inside of except(catch) scope'</span><span class="p">)</span>

<span class="k">print</span><span class="p">(</span><span class="s1">'5: outside of try/catch'</span><span class="p">)</span>
</pre>
      </div>
      <p>
       これを実行すると以下のような出力が得られます。
      </p>
      <div class="codehilite">
       <pre><span></span>python3 test.py
1: outside of try/catch
2: inside of try scope
3: inside of try scope
5: outside of try/catch
</pre>
      </div>
      <p>
       先ほどと異なり、エラーが発生していないのでprint('3: inside of try scope')が実行されています。
またエラーが発生しなかったので、except内の処理は呼びだされず '4: inside of except(catch) scope' の表示がなくなっていることもわかります。
そして、try/catchの外にある'1: outside of try/catch'と'5: outside of try/catch'は常に実行されています。
      </p>
      <p>
       これがPythonの簡単な一番簡単な例外処理のやりかたです。
Pythonではより細かく詳細な例外処理の実装を行うことも可能ですが、私は正直なところそれほど複雑なものは利用しません。
      </p>
      <p>
       ちなみに先程の文字列の find メソッド(与えられた文字列がなければ -1 を返す)とほとんど同じ
「期待されない場合に例外となる文字列のメソッド index」もあります。
具体的には以下のものとなります。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="n">index</span> <span class="o">=</span> <span class="s1">'12345'</span><span class="o">.</span><span class="n">index</span><span class="p">(</span><span class="s1">'23'</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="n">index</span><span class="p">)</span>
<span class="c1"># 1</span>

<span class="n">index</span> <span class="o">=</span> <span class="s1">'12345'</span><span class="o">.</span><span class="n">index</span><span class="p">(</span><span class="s1">'hello'</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="n">index</span><span class="p">)</span>
<span class="c1"># Traceback (most recent call last):</span>
<span class="c1"># ...</span>
<span class="c1"># ValueError: substring not found</span>
</pre>
      </div>
      <p>
       見てもらうとわかるように index も find と同様に文字列の位置を返すメソッドなのですが、
文字列が存在しない場合は例外が発生しています(実際には print 文より前に例外が発生しています)。
Try/Catch流で文字列が存在するか確認する関数 contains を実装すると以下のようになります。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">def</span> <span class="nf">contains</span><span class="p">(</span><span class="n">text1</span><span class="p">,</span> <span class="n">text2</span><span class="p">):</span>
  <span class="k">try</span><span class="p">:</span>
    <span class="n">text1</span><span class="o">.</span><span class="n">index</span><span class="p">(</span><span class="n">text2</span><span class="p">)</span>
    <span class="k">return</span> <span class="bp">True</span>
  <span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
    <span class="k">return</span> <span class="bp">False</span>

<span class="k">print</span><span class="p">(</span><span class="n">contains</span><span class="p">(</span><span class="s1">'12345'</span><span class="p">,</span> <span class="s1">'34'</span><span class="p">))</span>
<span class="c1"># True</span>

<span class="k">print</span><span class="p">(</span><span class="n">contains</span><span class="p">(</span><span class="s1">'12345'</span><span class="p">,</span> <span class="s1">'hello'</span><span class="p">))</span>
<span class="c1"># False</span>
</pre>
      </div>
      <p>
       今回のように文字列を探すという単純な処理であれば -1 を返すというルールを使うことで処理をしてしまうのが一般的です。
ただ、複雑な処理になるとより柔軟に対応できる例外処理方式を使うことが一般的です。
自分でプログラムを書く場合に、エラーが発生した場合に「例外を知らせる値を返す」か、
「例外を発生させてそれを処理してもらうか(後述)」のどちらを使うかは状況に応じて使い分けて下さい。
      </p>
      <h4>
       キャッチした例外を変数に格納
      </h4>
      <p>
       try/catchのexceptで指定した Except は先にも言ったように「クラス」です。
掴んだ例外はそのクラスのインスタンスとして取得することができます。
これもそれほど難しくないのでコードで確認してみます。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">print</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="k">try</span><span class="p">:</span>
  <span class="mi">5</span><span class="o">/</span><span class="mi">0</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="nb">type</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
  <span class="k">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="mi">2</span><span class="p">)</span>
</pre>
      </div>
      <p>
       exceptの後に、Exceptionに続けてeがあります。このeが例外を格納している変数です。
eは実際にはException型ではなく「Exceptionおよびその子クラスのいずれか」が格納されています。
これはクラスの継承で話した親クラスと子クラスの関係から実現できています。
上記コードではわざと 5/0 で例外を発生させてその例外を変数 e にキャッチ、typeとともにその内容を表示させています。
その出力を見てみます。
      </p>
      <div class="codehilite">
       <pre><span></span>1
&lt;class 'ZeroDivisionError'&gt;
division by zero
2
</pre>
      </div>
      <p>
       ZeroDivisionErrorが発生していることがわかります。
printさせれば、なぜZeroDivisionErrorになったかがわかります。
必ずしも例外を変数にいれる必要はありませんが、
自分が期待しないエラーはキャッチしてその中身を確認したほうがいい場合があります。
より詳細を知りたい場合は後述するエラーのトレースを使うと便利です。
      </p>
      <h4>
       意図的に例外を発生させる
      </h4>
      <p>
       プログラムが自分の意図しない状態になりそうなら、
その処理を中断するために「わざと例外を発生させる」というテクニックがあります。
たとえば簡単に天気予報の情報を得るためのライブラリを自分が書いているとしましょう。
当然ながらネットワークを使って外部から天気予報を取得することになるのでしょうが、
例えばネットワークが繋がっていない場合は天気を取得できません。
その場合、わざと例外を発生させることで「ライブラリを利用する側」に対して例外処理で問題に対応してもらうことができます。
Python はこの「例外を意図的に発生させる」ことを raise キーワードを使うことで実現できます。
簡単なサンプルを見てみます。
      </p>
      <div class="codehilite">
       <pre><span></span><span class="k">try</span><span class="p">:</span>
  <span class="n">a</span> <span class="o">=</span> <span class="mi">0</span>
  <span class="k">if</span><span class="p">(</span><span class="n">a</span> <span class="o">==</span> <span class="mi">0</span><span class="p">):</span>
    <span class="k">raise</span> <span class="ne">Exception</span><span class="p">(</span><span class="s1">'hello'</span><span class="p">)</span>
  <span class="mi">5</span><span class="o">/</span><span class="n">a</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
  <span class="k">print</span><span class="p">(</span><span class="nb">type</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
  <span class="k">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
</pre>
      </div>
      <p>
       前にお話したように0での除算は禁止されているため、割る前に除数が0でないかをチェックさせています。
そして、それが0であった場合は0 で割ってZeroDivisionErrorにさせるよりも、
「自分がコントロールできる形でわざとエラーとする」ことでZeroDivisionErrorとなることを避けています。
それを実現するためにraiseを使って、その後ろのExceptionを発生させています。
なお、Exceptionに与えられている'hello'はエラーの内容を記載しています。
そのあとのexceptでこのエラーをキャッチできるので、今回はraiseされたExceptionをつかんでいます。
      </p>
      <p>
       今回は例を簡単にするために発生させる例外を Exception としメッセージも hello でしたが、
実際はエラーに即した例外クラスを使い、メッセージにそのエラー原因を書くことになります。
例外クラスには後述する「自作の例外クラス」を使うことが多いです。
      </p>
      <p>
       このプログラムの出力は以下のようになります。
helloというメッセージを持つExceptionをキャッチできています。
      </p>
      <div class="codehilite">
       <pre><span></span>&lt;class 'Exception'&gt;
hello
</pre>
      </div>
      <p>
       このような処理を見て「どうせエラーになるのだから、
5/0でも raise でもどっちでもいいじゃないか」と思うかもしれません。
ただ、同じエラーであってもraiseでエラーとしている場合は「エラーを意図して発生させている」ことが明確にわかり、
それを自分でコントロールできていることがわかります。
一方、raiseでなく5/aでzeroDivisionErrorエラーが発生し、それをexceptで扱っていると、
それは「コードを読んだ人」にとっては意図せずエラーが発生しているように見えてしまいます。
      </p>
      <p>
       つまり、たとえ実装者が「期待したエラーハンドリング」だと思っていても、
ほかの人にはそう見えない可能性があるのです。
自分でエラーをコントロールする場合はエラーが発生してしまってから対処するのではなく、
エラーが発生する前に自前に対処をしてしまうようにすべきです。
      </p>
      <p>
       必ずしもraiseを使う必要はなく、たとえば期待されない値の代わりにデフォルトの設定で動くようにしたり、
場合によっては正しいアウトプットとともにプログラムを停止させてしまったり、
returnで関数を中断させてしまったりなど、さまざまな対処法があります。
ただ、raiseを使うべき場面というものもあるので、その存在だけは知っておいたほうがよいかもしれません。
      </p>
      <!-- GENERATED HTML END -->
      <!-- GENERATED HTML END -->
      <nav>
       <ul class="pager">
        <li id="previous-li">
         <a href="./117.html" id="previous-a">
          ← Previous
         </a>
        </li>
        <li>
         <a href="#">
          Page Top
         </a>
        </li>
        <li class="pager-next" id="next-li">
         <a href="./117.html" id="next-a">
          Next →
         </a>
        </li>
       </ul>
      </nav>
     </div>
     <!-- /.blog-main -->
     <div class="col-sm-3 col-sm-offset-1 u1-sidebar">
      <!-- SNS start -->
      <div class="sidebar-module">
       <ul class="social-buttons">
        <li>
         <!-- hatena -->
         <a class="hatena-bookmark-button" data-hatena-bookmark-lang="ja" data-hatena-bookmark-layout="basic-label-counter" href="http://b.hatena.ne.jp/entry/" title="このエントリーをはてなブックマークに追加">
          <img alt="このエントリーをはてなブックマークに追加" height="20" src="https://b.st-hatena.com/images/entry-button/button-only@2x.png" style="border: none;" width="20"/>
         </a>
         <script async="async" charset="utf-8" src="https://b.st-hatena.com/js/bookmark_button.js" type="text/javascript">
         </script>
        </li>
        <li>
         <!-- FB -->
         <div class="fb-like" data-action="like" data-layout="button_count" data-share="true" data-show-faces="false" data-size="small">
         </div>
         <div id="fb-root">
         </div>
         <script>
          (function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s);
                    js.id = id;
                    js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.9";
                    fjs.parentNode.insertBefore(js, fjs);
                  }(document, 'script', 'facebook-jssdk'));
         </script>
        </li>
        <li>
         <!-- twitter -->
         <a class="twitter-share-button" href="https://twitter.com/share">
          Tweet
         </a>
         <script>
          ! function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0],
                      p = /^http:/.test(d.location) ? 'http' : 'https';
                    if (!d.getElementById(id)) {
                      js = d.createElement(s);
                      js.id = id;
                      js.src = p + '://platform.twitter.com/widgets.js';
                      fjs.parentNode.insertBefore(js, fjs);
                    }
                  }(document, 'script', 'twitter-wjs');
         </script>
        </li>
        <li>
         <!-- G+ -->
         <!-- head 内か、body 終了タグの直前に次のタグを貼り付けてください。 -->
         <script async="" defer="" src="https://apis.google.com/js/platform.js">
          {
                    lang: 'ja'
                  }
         </script>
         <!-- 共有ボタン を表示したい位置に次のタグを貼り付けてください。 -->
         <div class="g-plus" data-action="share" data-annotation="none" data-height="24">
         </div>
        </li>
        <li>
         <!-- IN/Share -->
         <script src="//platform.linkedin.com/in.js" type="text/javascript">
          lang: ja_JP
         </script>
         <script data-counter="right" type="IN/Share">
         </script>
        </li>
       </ul>
      </div>
      <div class="print">
       <a href="./003_print.html">
        <img src="./assets/images/print.png"/>
        印刷する
       </a>
      </div>
      <!-- SNS end -->
      <div class="sidebar-module">
       <p class="sidebar-heading">
        Python入門
       </p>
       <ol class="list-unstyled">
        <li>
         <a href="./">
          トップページ
         </a>
        </li>
        <li>
         <a href="./download.html">
          ダウンロード
         </a>
        </li>
        <li>
         <a href="./qa.html">
          質問と回答
         </a>
        </li>
        <li>
         <a href="./books.html">
          おすすめPython書籍
         </a>
        </li>
        <li>
         <a href="./about.html">
          このページについて
         </a>
        </li>
       </ol>
      </div>
      <div class="sidebar-module">
       <p class="sidebar-heading">
        初級編
       </p>
       <ol class="list-unstyled">
        <li>
         <a href="./001.html">
          前書き
         </a>
        </li>
        <li>
         <a href="./002.html">
          目次
         </a>
        </li>
        <li>
         <a href="./003.html">
          Pythonプログラミング
         </a>
        </li>
        <li>
         <a href="./004.html">
          インストールと実行
         </a>
        </li>
        <li>
         <a href="./005.html">
          概要
         </a>
        </li>
        <li>
         <a href="./006.html">
          型と変数
         </a>
        </li>
        <li>
         <a href="./007.html">
          最重要な型
         </a>
        </li>
        <li>
         <a href="./008.html">
          制御構造
         </a>
        </li>
        <li>
         <a href="./009.html">
          関数
         </a>
        </li>
        <li>
         <a href="./010.html">
          モジュール
         </a>
        </li>
        <li>
         <a href="./011.html">
          オブジェクトとメソッド
         </a>
        </li>
        <li>
         <a href="./012.html">
          テキスト処理
         </a>
        </li>
        <li>
         <a href="./013.html">
          リスト再入門
         </a>
        </li>
        <li>
         <a href="./014.html">
          タプル
         </a>
        </li>
        <li>
         <a href="./015.html">
          セット
         </a>
        </li>
        <li>
         <a href="./016.html">
          辞書型
         </a>
        </li>
        <li>
         <a href="./017.html">
          None型
         </a>
        </li>
        <li>
         <a href="./018.html">
          ファイル処理
         </a>
        </li>
        <li>
         <a href="./019.html">
          基数と文字コード
         </a>
        </li>
        <li>
         <a href="./020.html">
          日本語の扱い
         </a>
        </li>
        <li>
         <a href="./021.html">
          プログラムへの入力
         </a>
        </li>
        <li>
         <a href="./022.html">
          関数の高度なトピック
         </a>
        </li>
        <li>
         <a href="./023.html">
          おわりに
         </a>
        </li>
       </ol>
      </div>
      <div class="sidebar-module">
       <p class="sidebar-heading">
        中級編
       </p>
       <ol class="list-unstyled">
        <li>
         <a href="./101.html">
          前書き
         </a>
        </li>
        <li>
         <a href="./102.html">
          目次
         </a>
        </li>
        <li>
         <a href="./103.html">
          オブジェクト指向を体験
         </a>
        </li>
        <li>
         <a href="./104.html">
          データ構造
         </a>
        </li>
        <li>
         <a href="./105.html">
          クラスとインスタンス化
         </a>
        </li>
        <li>
         <a href="./106.html">
          インスタンスとメソッド
         </a>
        </li>
        <li>
         <a href="./107.html">
          コンストラクタ
         </a>
        </li>
        <li>
         <a href="./108.html">
          self
         </a>
        </li>
        <li>
         <a href="./109.html">
          情報の隠蔽
         </a>
        </li>
        <li>
         <a href="./110.html">
          オブジェクトの役割
         </a>
        </li>
        <li>
         <a href="./111.html">
          関数型プログラミング
         </a>
        </li>
        <li>
         <a href="./112.html">
          ゲーム作り
         </a>
        </li>
        <li>
         <a href="./113.html">
          クラスの継承
         </a>
        </li>
        <li>
         <a href="./114.html">
          メソッドのオーバーライド
         </a>
        </li>
        <li>
         <a href="./115.html">
          GUIで継承を学ぶ
         </a>
        </li>
        <li>
         <a href="./116.html">
          クラスの高度なトピック
         </a>
        </li>
        <li>
         <a href="./117.html">
          ドキュメンテーション
         </a>
        </li>
        <li>
         <a href="./118.html">
          例外処理の基礎
         </a>
        </li>
        <li>
         <a href="./119.html">
          例外クラス
         </a>
        </li>
        <li>
         <a href="./120.html">
          高度な例外処理
         </a>
        </li>
        <li>
         <a href="./121.html">
          終わりに
         </a>
        </li>
       </ol>
      </div>
      <!-- amazon -->
      <div class="sidebar-module">
       <script type="text/javascript">
        amazon_ad_tag = "grit-22";
              amazon_ad_width = "300";
              amazon_ad_height = "250";
              amazon_ad_link_target = "new";
       </script>
       <script src="http://ir-jp.amazon-adsystem.com/s/ads.js">
       </script>
      </div>
      <!-- amazon end-->
      <div class="sidebar-module">
       <p class="sidebar-heading">
        Python入門
       </p>
       <ol class="list-unstyled">
        <li>
         <a href="https://github.com/yuichi110/www.yuichi.com-python" target="_blank">
          <span class="fa fa-github">
          </span>
          GitHub Repository
         </a>
        </li>
        <li>
         <a href="https://twitter.com/yuichi110" target="_blank">
          <i class="fa fa-twitter">
          </i>
          Twitter
         </a>
        </li>
        <li>
         <a href="https://www.linkedin.com/in/yuichiito/" target="_blank">
          <span class="fa fa-linkedin">
          </span>
          Linkedin (英語)
         </a>
        </li>
        <li class="li-none">
         <a href="#" id="rw_email_contact">
          <span class="fa fa-envelope">
           Mail
          </span>
         </a>
         <script type="text/javascript">
          var _rwObsfuscatedHref0 = "mai";
                  var _rwObsfuscatedHref1 = "lto";
                  var _rwObsfuscatedHref2 = ":yu";
                  var _rwObsfuscatedHref3 = "ich";
                  var _rwObsfuscatedHref4 = "i@y";
                  var _rwObsfuscatedHref5 = "uic";
                  var _rwObsfuscatedHref6 = "hi.";
                  var _rwObsfuscatedHref7 = "com";
                  var _rwObsfuscatedHref = _rwObsfuscatedHref0 + _rwObsfuscatedHref1 + _rwObsfuscatedHref2 + _rwObsfuscatedHref3 + _rwObsfuscatedHref4 + _rwObsfuscatedHref5 + _rwObsfuscatedHref6 + _rwObsfuscatedHref7;
                  document.getElementById("rw_email_contact").href = _rwObsfuscatedHref;
         </script>
        </li>
       </ol>
      </div>
      <div class="sidebar-module">
       <!-- padding for side bar -->
       <div class="hidden-xs">
        <p style="height:500px">
        </p>
       </div>
      </div>
     </div>
     <!-- /.blog-sidebar -->
    </div>
    <!-- /.row -->
   </div>
   <!-- /.container -->
   <footer>
    <div class="u1-footer-top">
    </div>
    <div class="u1-footer">
     <p>
      Copyright © 2017 Yuichi Ito All Rights Reserved.
     </p>
     <p align="center">
      修正依頼がある場合は右ページよりページURLと問題箇所を指摘願います。
      <a href="https://github.com/yuichi110/www.yuichi.com-python/issues">
       <span class="fa fa-github">
       </span>
       Git Hub Issues
      </a>
     </p>
    </div>
   </footer>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
   </script>
   <script src="./assets/js/bootstrap.min.js">
   </script>
   <script src="./assets/js/delete_useless_dom.js">
   </script>
   <!-- GOOGLE ANALYTICS -->
   <script>
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
          m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
      })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
      ga('create', 'UA-4830860-7', 'auto');
      ga('send', 'pageview');
   </script>
  </div>
  <!-- end of background -->
 </body>
</html>
